# Generated by Django 4.2.7 on 2025-01-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_number_plate', models.CharField(max_length=15)),
                ('time_detected', models.DateTimeField()),
            ],
            options={
                'db_table': 'AlertTable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dldetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licensenumber', models.CharField(max_length=20, unique=True)),
                ('licensetype', models.CharField(blank=True, max_length=50, null=True)),
                ('issuedate', models.DateField()),
                ('expirydate', models.DateField()),
            ],
            options={
                'db_table': 'dldetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Generalpeopledetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'generalpeopledetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suspiciouspersondetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timehappened', models.DateTimeField()),
                ('felony_catogry', models.CharField(choices=[('Expired_Status', 'Expired Status'), ('Past_Felony', 'Past Felony'), ('Wanted', 'Wanted')], max_length=14)),
                ('felony_type', models.CharField(blank=True, max_length=25, null=True)),
                ('reasondetail', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'suspiciouspersondetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suspiciousvehicledetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timehappened', models.DateTimeField()),
                ('felony_catogory', models.CharField(choices=[('Expired_Status', 'Expired Status'), ('Past_Felony', 'Past Felony'), ('Wanted', 'Wanted')], max_length=14)),
                ('felony_type', models.CharField(blank=True, max_length=25, null=True)),
                ('reasondetail', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'suspiciousvehicledetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicledetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberplate', models.CharField(max_length=15, unique=True)),
                ('vehicletype', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_date', models.DateField()),
                ('registration_status', models.CharField(choices=[('Valid', 'Valid'), ('Expired', 'Expired')], max_length=7)),
                ('insurance_status', models.CharField(choices=[('Valid', 'Valid'), ('Expired', 'Expired')], max_length=7)),
                ('puc_status', models.CharField(choices=[('Valid', 'Valid'), ('Expired', 'Expired')], max_length=7)),
            ],
            options={
                'db_table': 'vehicledetails',
                'managed': False,
            },
        ),
    ]
